### PR TITLE
Use XML audio, conf is deprecated from android N

### PR DESCRIPTION
**Pull request by joe2k01**
Looking at the proprietary blobs list I saw that there is the policy configuration in the xml format, which is introduced in android N

### CODE REVIEW

**Comment by leskal** [comment]
According this: https://source.android.com/devices/audio/implement-policy

the USE_XML_AUDIO_POLICY_CONF := 1 add supports for audio_policy.conf so we don't have to delete it

**Comment by joe2k01** [comment]
"Note: Android 7.0 preserves support for using audio_policy.conf; this legacy format is used by default. To use the XML file format, include the build option USE_XML_AUDIO_POLICY_CONF := 1 in device makefile."
From my understanding to use the .conf you don't need the flag

**Comment by leskal** [comment]
Ok, so why remove the audio_policy.conf ?

**Comment by joe2k01** [comment]
It is not needed

**Comment by leskal** [comment]
why?

**Comment by joe2k01** [comment]
Because android 7 loads the XML configuration instead of the .conf

**Comment by leskal** [comment]
you mean this file https://github.com/leskal/android_vendor_elephone_p9000/blob/test-N/proprietary/etc/audio_policy_configuration.xml ?

**Comment by tribual** [comment]
Yeah, also read about this. Think this should be right file...

**Comment by joe2k01** [comment]
@leskal the file you linked is the one that will be loaded with the flag

**Comment by leskal** [comment]
Ok thanks for the info, for now i am not using these files because i am trying to make the N boot to P9000, so i will test it when i manage to boot to N, also, do these files require specific audio.primary.mt6755.so and other related files for audio?

**Comment by joe2k01** [comment]
All the non-generic blobs are needed. BTW, with latest ramdisk and sepolicy is still not booting?

**Comment by joe2k01** [comment]
@leskal take a look at the new commit

**Comment by leskal** [comment]
Ok @joe2k01 thanks for your help, i will test it tonight 😉

**Comment by joe2k01** [comment]
@leskal before building apply 5088292

**Pull request closed without merging**
